/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package WSDL2_0.provider;

import WSDL2_0.util.WSDL2_0AdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class WSDL2_0ItemProviderAdapterFactory extends WSDL2_0AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public WSDL2_0ItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Schema} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SchemaItemProvider schemaItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Schema}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSchemaAdapter() {
		if (schemaItemProvider == null) {
			schemaItemProvider = new SchemaItemProvider(this);
		}

		return schemaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.AdicionalInformationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AdicionalInformationTypeItemProvider adicionalInformationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.AdicionalInformationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAdicionalInformationTypeAdapter() {
		if (adicionalInformationTypeItemProvider == null) {
			adicionalInformationTypeItemProvider = new AdicionalInformationTypeItemProvider(this);
		}

		return adicionalInformationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.TypeRef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeRefItemProvider typeRefItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.TypeRef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeRefAdapter() {
		if (typeRefItemProvider == null) {
			typeRefItemProvider = new TypeRefItemProvider(this);
		}

		return typeRefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.IncludeXMLSchema} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IncludeXMLSchemaItemProvider includeXMLSchemaItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.IncludeXMLSchema}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIncludeXMLSchemaAdapter() {
		if (includeXMLSchemaItemProvider == null) {
			includeXMLSchemaItemProvider = new IncludeXMLSchemaItemProvider(this);
		}

		return includeXMLSchemaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.ImportXMLSchema} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportXMLSchemaItemProvider importXMLSchemaItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.ImportXMLSchema}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportXMLSchemaAdapter() {
		if (importXMLSchemaItemProvider == null) {
			importXMLSchemaItemProvider = new ImportXMLSchemaItemProvider(this);
		}

		return importXMLSchemaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Redefine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RedefineItemProvider redefineItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Redefine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRedefineAdapter() {
		if (redefineItemProvider == null) {
			redefineItemProvider = new RedefineItemProvider(this);
		}

		return redefineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Annotation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationItemProvider annotationItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Annotation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationAdapter() {
		if (annotationItemProvider == null) {
			annotationItemProvider = new AnnotationItemProvider(this);
		}

		return annotationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.ComplexType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComplexTypeItemProvider complexTypeItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.ComplexType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComplexTypeAdapter() {
		if (complexTypeItemProvider == null) {
			complexTypeItemProvider = new ComplexTypeItemProvider(this);
		}

		return complexTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Element} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElementItemProvider elementItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Element}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElementAdapter() {
		if (elementItemProvider == null) {
			elementItemProvider = new ElementItemProvider(this);
		}

		return elementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.ElementImported} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElementImportedItemProvider elementImportedItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.ElementImported}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElementImportedAdapter() {
		if (elementImportedItemProvider == null) {
			elementImportedItemProvider = new ElementImportedItemProvider(this);
		}

		return elementImportedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Attribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeItemProvider attributeItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Attribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeAdapter() {
		if (attributeItemProvider == null) {
			attributeItemProvider = new AttributeItemProvider(this);
		}

		return attributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.AttributeGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeGroupItemProvider attributeGroupItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.AttributeGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeGroupAdapter() {
		if (attributeGroupItemProvider == null) {
			attributeGroupItemProvider = new AttributeGroupItemProvider(this);
		}

		return attributeGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Group} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GroupItemProvider groupItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Group}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGroupAdapter() {
		if (groupItemProvider == null) {
			groupItemProvider = new GroupItemProvider(this);
		}

		return groupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Notation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NotationItemProvider notationItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Notation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNotationAdapter() {
		if (notationItemProvider == null) {
			notationItemProvider = new NotationItemProvider(this);
		}

		return notationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.SimpleContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SimpleContentItemProvider simpleContentItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.SimpleContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSimpleContentAdapter() {
		if (simpleContentItemProvider == null) {
			simpleContentItemProvider = new SimpleContentItemProvider(this);
		}

		return simpleContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.ComplexContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComplexContentItemProvider complexContentItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.ComplexContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComplexContentAdapter() {
		if (complexContentItemProvider == null) {
			complexContentItemProvider = new ComplexContentItemProvider(this);
		}

		return complexContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Unique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UniqueItemProvider uniqueItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Unique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUniqueAdapter() {
		if (uniqueItemProvider == null) {
			uniqueItemProvider = new UniqueItemProvider(this);
		}

		return uniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Key} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KeyItemProvider keyItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Key}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKeyAdapter() {
		if (keyItemProvider == null) {
			keyItemProvider = new KeyItemProvider(this);
		}

		return keyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.KeyRef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KeyRefItemProvider keyRefItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.KeyRef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKeyRefAdapter() {
		if (keyRefItemProvider == null) {
			keyRefItemProvider = new KeyRefItemProvider(this);
		}

		return keyRefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.AnyAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnyAttributeItemProvider anyAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.AnyAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnyAttributeAdapter() {
		if (anyAttributeItemProvider == null) {
			anyAttributeItemProvider = new AnyAttributeItemProvider(this);
		}

		return anyAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Extension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtensionItemProvider extensionItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Extension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtensionAdapter() {
		if (extensionItemProvider == null) {
			extensionItemProvider = new ExtensionItemProvider(this);
		}

		return extensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Selector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectorItemProvider selectorItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Selector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectorAdapter() {
		if (selectorItemProvider == null) {
			selectorItemProvider = new SelectorItemProvider(this);
		}

		return selectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Field} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldItemProvider fieldItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Field}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldAdapter() {
		if (fieldItemProvider == null) {
			fieldItemProvider = new FieldItemProvider(this);
		}

		return fieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.AppInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AppInfoItemProvider appInfoItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.AppInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAppInfoAdapter() {
		if (appInfoItemProvider == null) {
			appInfoItemProvider = new AppInfoItemProvider(this);
		}

		return appInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.DocumentationXMLSchema} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentationXMLSchemaItemProvider documentationXMLSchemaItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.DocumentationXMLSchema}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentationXMLSchemaAdapter() {
		if (documentationXMLSchemaItemProvider == null) {
			documentationXMLSchemaItemProvider = new DocumentationXMLSchemaItemProvider(this);
		}

		return documentationXMLSchemaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Any} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnyItemProvider anyItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Any}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnyAdapter() {
		if (anyItemProvider == null) {
			anyItemProvider = new AnyItemProvider(this);
		}

		return anyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.All} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AllItemProvider allItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.All}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAllAdapter() {
		if (allItemProvider == null) {
			allItemProvider = new AllItemProvider(this);
		}

		return allItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Choice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoiceItemProvider choiceItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Choice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoiceAdapter() {
		if (choiceItemProvider == null) {
			choiceItemProvider = new ChoiceItemProvider(this);
		}

		return choiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.SequenceType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SequenceTypeItemProvider sequenceTypeItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.SequenceType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSequenceTypeAdapter() {
		if (sequenceTypeItemProvider == null) {
			sequenceTypeItemProvider = new SequenceTypeItemProvider(this);
		}

		return sequenceTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.SimpleType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SimpleTypeItemProvider simpleTypeItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.SimpleType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSimpleTypeAdapter() {
		if (simpleTypeItemProvider == null) {
			simpleTypeItemProvider = new SimpleTypeItemProvider(this);
		}

		return simpleTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.List} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListItemProvider listItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.List}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListAdapter() {
		if (listItemProvider == null) {
			listItemProvider = new ListItemProvider(this);
		}

		return listItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Union} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnionItemProvider unionItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Union}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnionAdapter() {
		if (unionItemProvider == null) {
			unionItemProvider = new UnionItemProvider(this);
		}

		return unionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Restriction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RestrictionItemProvider restrictionItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Restriction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRestrictionAdapter() {
		if (restrictionItemProvider == null) {
			restrictionItemProvider = new RestrictionItemProvider(this);
		}

		return restrictionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.MinInclusive} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MinInclusiveItemProvider minInclusiveItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.MinInclusive}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMinInclusiveAdapter() {
		if (minInclusiveItemProvider == null) {
			minInclusiveItemProvider = new MinInclusiveItemProvider(this);
		}

		return minInclusiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.MinExclusive} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MinExclusiveItemProvider minExclusiveItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.MinExclusive}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMinExclusiveAdapter() {
		if (minExclusiveItemProvider == null) {
			minExclusiveItemProvider = new MinExclusiveItemProvider(this);
		}

		return minExclusiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.MaxInclusive} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MaxInclusiveItemProvider maxInclusiveItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.MaxInclusive}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMaxInclusiveAdapter() {
		if (maxInclusiveItemProvider == null) {
			maxInclusiveItemProvider = new MaxInclusiveItemProvider(this);
		}

		return maxInclusiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.MaxExclusive} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MaxExclusiveItemProvider maxExclusiveItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.MaxExclusive}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMaxExclusiveAdapter() {
		if (maxExclusiveItemProvider == null) {
			maxExclusiveItemProvider = new MaxExclusiveItemProvider(this);
		}

		return maxExclusiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.TotalDigits} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TotalDigitsItemProvider totalDigitsItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.TotalDigits}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTotalDigitsAdapter() {
		if (totalDigitsItemProvider == null) {
			totalDigitsItemProvider = new TotalDigitsItemProvider(this);
		}

		return totalDigitsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.FractionDigits} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FractionDigitsItemProvider fractionDigitsItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.FractionDigits}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFractionDigitsAdapter() {
		if (fractionDigitsItemProvider == null) {
			fractionDigitsItemProvider = new FractionDigitsItemProvider(this);
		}

		return fractionDigitsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Pattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PatternItemProvider patternItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Pattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPatternAdapter() {
		if (patternItemProvider == null) {
			patternItemProvider = new PatternItemProvider(this);
		}

		return patternItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Enumeration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationItemProvider enumerationItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Enumeration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationAdapter() {
		if (enumerationItemProvider == null) {
			enumerationItemProvider = new EnumerationItemProvider(this);
		}

		return enumerationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.WhiteSpace} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WhiteSpaceItemProvider whiteSpaceItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.WhiteSpace}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhiteSpaceAdapter() {
		if (whiteSpaceItemProvider == null) {
			whiteSpaceItemProvider = new WhiteSpaceItemProvider(this);
		}

		return whiteSpaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Length} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LengthItemProvider lengthItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Length}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLengthAdapter() {
		if (lengthItemProvider == null) {
			lengthItemProvider = new LengthItemProvider(this);
		}

		return lengthItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.MaxLength} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MaxLengthItemProvider maxLengthItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.MaxLength}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMaxLengthAdapter() {
		if (maxLengthItemProvider == null) {
			maxLengthItemProvider = new MaxLengthItemProvider(this);
		}

		return maxLengthItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.MinLength} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MinLengthItemProvider minLengthItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.MinLength}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMinLengthAdapter() {
		if (minLengthItemProvider == null) {
			minLengthItemProvider = new MinLengthItemProvider(this);
		}

		return minLengthItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Text} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextItemProvider textItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Text}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextAdapter() {
		if (textItemProvider == null) {
			textItemProvider = new TextItemProvider(this);
		}

		return textItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Object} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectItemProvider objectItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Object}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectAdapter() {
		if (objectItemProvider == null) {
			objectItemProvider = new ObjectItemProvider(this);
		}

		return objectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Description} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DescriptionItemProvider descriptionItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Description}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDescriptionAdapter() {
		if (descriptionItemProvider == null) {
			descriptionItemProvider = new DescriptionItemProvider(this);
		}

		return descriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Interface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceItemProvider interfaceItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Interface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceAdapter() {
		if (interfaceItemProvider == null) {
			interfaceItemProvider = new InterfaceItemProvider(this);
		}

		return interfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.InterfaceFault} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceFaultItemProvider interfaceFaultItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.InterfaceFault}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceFaultAdapter() {
		if (interfaceFaultItemProvider == null) {
			interfaceFaultItemProvider = new InterfaceFaultItemProvider(this);
		}

		return interfaceFaultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.InterfaceOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceOperationItemProvider interfaceOperationItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.InterfaceOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceOperationAdapter() {
		if (interfaceOperationItemProvider == null) {
			interfaceOperationItemProvider = new InterfaceOperationItemProvider(this);
		}

		return interfaceOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.InterfaceInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceInputItemProvider interfaceInputItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.InterfaceInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceInputAdapter() {
		if (interfaceInputItemProvider == null) {
			interfaceInputItemProvider = new InterfaceInputItemProvider(this);
		}

		return interfaceInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.InterfaceOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceOutputItemProvider interfaceOutputItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.InterfaceOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceOutputAdapter() {
		if (interfaceOutputItemProvider == null) {
			interfaceOutputItemProvider = new InterfaceOutputItemProvider(this);
		}

		return interfaceOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.InterfaceInfault} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceInfaultItemProvider interfaceInfaultItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.InterfaceInfault}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceInfaultAdapter() {
		if (interfaceInfaultItemProvider == null) {
			interfaceInfaultItemProvider = new InterfaceInfaultItemProvider(this);
		}

		return interfaceInfaultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.InterfaceOutfault} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceOutfaultItemProvider interfaceOutfaultItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.InterfaceOutfault}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceOutfaultAdapter() {
		if (interfaceOutfaultItemProvider == null) {
			interfaceOutfaultItemProvider = new InterfaceOutfaultItemProvider(this);
		}

		return interfaceOutfaultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Binding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BindingItemProvider bindingItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Binding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBindingAdapter() {
		if (bindingItemProvider == null) {
			bindingItemProvider = new BindingItemProvider(this);
		}

		return bindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.BindingFault} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BindingFaultItemProvider bindingFaultItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.BindingFault}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBindingFaultAdapter() {
		if (bindingFaultItemProvider == null) {
			bindingFaultItemProvider = new BindingFaultItemProvider(this);
		}

		return bindingFaultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.BindingOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BindingOperationItemProvider bindingOperationItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.BindingOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBindingOperationAdapter() {
		if (bindingOperationItemProvider == null) {
			bindingOperationItemProvider = new BindingOperationItemProvider(this);
		}

		return bindingOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.BindingInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BindingInputItemProvider bindingInputItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.BindingInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBindingInputAdapter() {
		if (bindingInputItemProvider == null) {
			bindingInputItemProvider = new BindingInputItemProvider(this);
		}

		return bindingInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.BindingOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BindingOutputItemProvider bindingOutputItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.BindingOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBindingOutputAdapter() {
		if (bindingOutputItemProvider == null) {
			bindingOutputItemProvider = new BindingOutputItemProvider(this);
		}

		return bindingOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.BindingInfault} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BindingInfaultItemProvider bindingInfaultItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.BindingInfault}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBindingInfaultAdapter() {
		if (bindingInfaultItemProvider == null) {
			bindingInfaultItemProvider = new BindingInfaultItemProvider(this);
		}

		return bindingInfaultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.BindingOutfault} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BindingOutfaultItemProvider bindingOutfaultItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.BindingOutfault}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBindingOutfaultAdapter() {
		if (bindingOutfaultItemProvider == null) {
			bindingOutfaultItemProvider = new BindingOutfaultItemProvider(this);
		}

		return bindingOutfaultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Service} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceItemProvider serviceItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Service}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAdapter() {
		if (serviceItemProvider == null) {
			serviceItemProvider = new ServiceItemProvider(this);
		}

		return serviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.EndPoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EndPointItemProvider endPointItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.EndPoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEndPointAdapter() {
		if (endPointItemProvider == null) {
			endPointItemProvider = new EndPointItemProvider(this);
		}

		return endPointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.ElementType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElementTypeItemProvider elementTypeItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.ElementType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElementTypeAdapter() {
		if (elementTypeItemProvider == null) {
			elementTypeItemProvider = new ElementTypeItemProvider(this);
		}

		return elementTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Include} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IncludeItemProvider includeItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Include}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIncludeAdapter() {
		if (includeItemProvider == null) {
			includeItemProvider = new IncludeItemProvider(this);
		}

		return includeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Import} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportItemProvider importItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportAdapter() {
		if (importItemProvider == null) {
			importItemProvider = new ImportItemProvider(this);
		}

		return importItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Documentation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentationItemProvider documentationItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Documentation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentationAdapter() {
		if (documentationItemProvider == null) {
			documentationItemProvider = new DocumentationItemProvider(this);
		}

		return documentationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Namespace} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamespaceItemProvider namespaceItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Namespace}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamespaceAdapter() {
		if (namespaceItemProvider == null) {
			namespaceItemProvider = new NamespaceItemProvider(this);
		}

		return namespaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Wsoap_Module} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Wsoap_ModuleItemProvider wsoap_ModuleItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Wsoap_Module}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWsoap_ModuleAdapter() {
		if (wsoap_ModuleItemProvider == null) {
			wsoap_ModuleItemProvider = new Wsoap_ModuleItemProvider(this);
		}

		return wsoap_ModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Wsoap_Header} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Wsoap_HeaderItemProvider wsoap_HeaderItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Wsoap_Header}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWsoap_HeaderAdapter() {
		if (wsoap_HeaderItemProvider == null) {
			wsoap_HeaderItemProvider = new Wsoap_HeaderItemProvider(this);
		}

		return wsoap_HeaderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WSDL2_0.Whttp_Header} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Whttp_HeaderItemProvider whttp_HeaderItemProvider;

	/**
	 * This creates an adapter for a {@link WSDL2_0.Whttp_Header}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhttp_HeaderAdapter() {
		if (whttp_HeaderItemProvider == null) {
			whttp_HeaderItemProvider = new Whttp_HeaderItemProvider(this);
		}

		return whttp_HeaderItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (schemaItemProvider != null) schemaItemProvider.dispose();
		if (adicionalInformationTypeItemProvider != null) adicionalInformationTypeItemProvider.dispose();
		if (typeRefItemProvider != null) typeRefItemProvider.dispose();
		if (includeXMLSchemaItemProvider != null) includeXMLSchemaItemProvider.dispose();
		if (importXMLSchemaItemProvider != null) importXMLSchemaItemProvider.dispose();
		if (redefineItemProvider != null) redefineItemProvider.dispose();
		if (annotationItemProvider != null) annotationItemProvider.dispose();
		if (complexTypeItemProvider != null) complexTypeItemProvider.dispose();
		if (elementItemProvider != null) elementItemProvider.dispose();
		if (elementImportedItemProvider != null) elementImportedItemProvider.dispose();
		if (attributeItemProvider != null) attributeItemProvider.dispose();
		if (attributeGroupItemProvider != null) attributeGroupItemProvider.dispose();
		if (groupItemProvider != null) groupItemProvider.dispose();
		if (notationItemProvider != null) notationItemProvider.dispose();
		if (simpleContentItemProvider != null) simpleContentItemProvider.dispose();
		if (complexContentItemProvider != null) complexContentItemProvider.dispose();
		if (uniqueItemProvider != null) uniqueItemProvider.dispose();
		if (keyItemProvider != null) keyItemProvider.dispose();
		if (keyRefItemProvider != null) keyRefItemProvider.dispose();
		if (anyAttributeItemProvider != null) anyAttributeItemProvider.dispose();
		if (extensionItemProvider != null) extensionItemProvider.dispose();
		if (selectorItemProvider != null) selectorItemProvider.dispose();
		if (fieldItemProvider != null) fieldItemProvider.dispose();
		if (appInfoItemProvider != null) appInfoItemProvider.dispose();
		if (documentationXMLSchemaItemProvider != null) documentationXMLSchemaItemProvider.dispose();
		if (anyItemProvider != null) anyItemProvider.dispose();
		if (allItemProvider != null) allItemProvider.dispose();
		if (choiceItemProvider != null) choiceItemProvider.dispose();
		if (sequenceTypeItemProvider != null) sequenceTypeItemProvider.dispose();
		if (simpleTypeItemProvider != null) simpleTypeItemProvider.dispose();
		if (listItemProvider != null) listItemProvider.dispose();
		if (unionItemProvider != null) unionItemProvider.dispose();
		if (restrictionItemProvider != null) restrictionItemProvider.dispose();
		if (minInclusiveItemProvider != null) minInclusiveItemProvider.dispose();
		if (minExclusiveItemProvider != null) minExclusiveItemProvider.dispose();
		if (maxInclusiveItemProvider != null) maxInclusiveItemProvider.dispose();
		if (maxExclusiveItemProvider != null) maxExclusiveItemProvider.dispose();
		if (totalDigitsItemProvider != null) totalDigitsItemProvider.dispose();
		if (fractionDigitsItemProvider != null) fractionDigitsItemProvider.dispose();
		if (patternItemProvider != null) patternItemProvider.dispose();
		if (enumerationItemProvider != null) enumerationItemProvider.dispose();
		if (whiteSpaceItemProvider != null) whiteSpaceItemProvider.dispose();
		if (lengthItemProvider != null) lengthItemProvider.dispose();
		if (maxLengthItemProvider != null) maxLengthItemProvider.dispose();
		if (minLengthItemProvider != null) minLengthItemProvider.dispose();
		if (textItemProvider != null) textItemProvider.dispose();
		if (objectItemProvider != null) objectItemProvider.dispose();
		if (descriptionItemProvider != null) descriptionItemProvider.dispose();
		if (interfaceItemProvider != null) interfaceItemProvider.dispose();
		if (interfaceFaultItemProvider != null) interfaceFaultItemProvider.dispose();
		if (interfaceOperationItemProvider != null) interfaceOperationItemProvider.dispose();
		if (interfaceInputItemProvider != null) interfaceInputItemProvider.dispose();
		if (interfaceOutputItemProvider != null) interfaceOutputItemProvider.dispose();
		if (interfaceInfaultItemProvider != null) interfaceInfaultItemProvider.dispose();
		if (interfaceOutfaultItemProvider != null) interfaceOutfaultItemProvider.dispose();
		if (bindingItemProvider != null) bindingItemProvider.dispose();
		if (bindingFaultItemProvider != null) bindingFaultItemProvider.dispose();
		if (bindingOperationItemProvider != null) bindingOperationItemProvider.dispose();
		if (bindingInputItemProvider != null) bindingInputItemProvider.dispose();
		if (bindingOutputItemProvider != null) bindingOutputItemProvider.dispose();
		if (bindingInfaultItemProvider != null) bindingInfaultItemProvider.dispose();
		if (bindingOutfaultItemProvider != null) bindingOutfaultItemProvider.dispose();
		if (serviceItemProvider != null) serviceItemProvider.dispose();
		if (endPointItemProvider != null) endPointItemProvider.dispose();
		if (elementTypeItemProvider != null) elementTypeItemProvider.dispose();
		if (includeItemProvider != null) includeItemProvider.dispose();
		if (importItemProvider != null) importItemProvider.dispose();
		if (documentationItemProvider != null) documentationItemProvider.dispose();
		if (namespaceItemProvider != null) namespaceItemProvider.dispose();
		if (wsoap_ModuleItemProvider != null) wsoap_ModuleItemProvider.dispose();
		if (wsoap_HeaderItemProvider != null) wsoap_HeaderItemProvider.dispose();
		if (whttp_HeaderItemProvider != null) whttp_HeaderItemProvider.dispose();
	}

}
